// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Todo.Data
{
    public partial class Task
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public int? UserId { get; set; }

        public virtual User User { get; set; }
    }
}